### PR TITLE
Megarparsec fixes, remove redundant imports, release, update nightly version date

### LINKED ISSUE #67: slack-web-0.2.0.7: MessageParser.hs: error: Variable not in scope: anyChar
In Stackage Nightly:

```
Building library for slack-web-0.2.0.7..
[ 1 of 12] Compiling Web.Slack.Types  ( src/Web/Slack/Types.hs, dist/build/Web/Slack/Types.o )

src/Web/Slack/Types.hs:28:1: warning: [-Wunused-imports]
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
   |
28 | import Data.Monoid
   | ^^^^^^^^^^^^^^^^^^
[ 2 of 12] Compiling Web.Slack.MessageParser ( src/Web/Slack/MessageParser.hs, dist/build/Web/Slack/MessageParser.o )

src/Web/Slack/MessageParser.hs:141:29: error:
    Variable not in scope:
      anyChar :: ParsecT MegaparsecError Text Identity Char
    |
141 |   (string "```" >> manyTill anyChar (string "```"))
    |                             ^^^^^^^
```

### PR DESCRIPTION
**Pull request by emmanueltouzery**
fixes #67 

* update circleci base docker image
* megaparsec: explicit version constraints, support megaparsec7
* update nightly version date to the latest nightly
* remove now redundant import: Data.Monoid
* release 0.2.0.8

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
hmm right with this change we don't build on the previous LTS. I'll make it so we support the previous LTS and the current nightly too and update the PR

File: src/Web/Slack/Types.hs [hunk 1]
```diff
@@ -25,7 +25,6 @@ module Web.Slack.Types
 import Data.Aeson
 
 -- base
-import Data.Monoid
```
Comment (jpvillaisaza) [inline src/Web/Slack/Types.hs:28]: Are the `import Data.Monoid` only redundant when using newer versions (will this stop working for older versions)?

Comment (emmanueltouzery) [reply src/Web/Slack/Types.hs:28]: yes absolutely. on the other hand, if we want to keep them due to old versions, we might want to think about #ifdef pragmas, or to disable -Wunused-imports. This is almost an ancient thing otherwise, by haskell standards. https://ghc.haskell.org/trac/ghc/wiki/Migration/7.10 -- This import is redundant since ghc 7.10 (base 4.8). Seems to be 2015. https://www.haskell.org/ghc/download_ghc_7_10_1.html -- you are correct though, if we want to drop that support, we could indicate it in the cabal file through constraints (concretely, base>=4.8).

So I guess:

1. drop -Wunused-imports
2. #if for the import on the `base` version to support both versions without warnings
3. require base >=4.8 (2015)

Comment (jpvillaisaza) [reply src/Web/Slack/Types.hs:28]: I'm okay with 3, require `base >= 4.8`.

Comment (emmanueltouzery) [reply src/Web/Slack/Types.hs:28]: hmm wait, we already have `base >= 4.9` in the .cabal so this seems like a non-issue :) in that case the PR is correct, we never need this import given the build constraints.

**Comment by emmanueltouzery** [comment]
btw another question about the merge. I split the commits so I'd probably do "rebase and merge this time". Let me know if you prefer "squash and merge".

**Comment by jpvillaisaza** [comment]
Rebase and merge works if the commits are organized that way. 👍

**Comment by emmanueltouzery** [comment]
I deployed the new version on hackage. Turns out, I may have broken some old versions with the Data.Monoid change. The [build matrix](https://matrix.hackage.haskell.org/#/package/slack-web/0.2.0.8/ghc-8.2.2@1541448477) shows failures on ghc 8.2 & 8.0

src/Web/Slack/Types.hs:70:74: error:
    • Variable not in scope: (<>) :: Text -> [Char] -> Text
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Prelude), ‘*>’ (imported from Prelude),
        ‘<$’ (imported from Prelude)

It looks like the `Data.Monoid` import was needed for `<>` actually up to base-4.11

https://hackage.haskell.org/package/base-4.11.1.0/changelog

> Make Semigroup a superclass of Monoid; export Semigroup((<>)) from Prelude; remove Monoid reexport from Data.Semigroup (#14191).

If you want I can make a PR with `#if`. GHC 8.2 is 2017, not that old.
